version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./iot/mosquitto.conf:/mosquitto/config/mosquitto.conf